Traceback (most recent call last):
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mcburton/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pizza_tuple = ('cheese', 'pepperoni', 'veggie', 'margherita')
pizza_tuple.insert(1,'Hawaiian')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [47][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m pizza_tuple [38;5;241m=[39m ([38;5;124m'[39m[38;5;124mcheese[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mpepperoni[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mveggie[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mmargherita[39m[38;5;124m'[39m)
[0;32m----> 2[0m [43mpizza_tuple[49m[38;5;241;43m.[39;49m[43minsert[49m([38;5;241m1[39m,[38;5;124m'[39m[38;5;124mHawaiian[39m[38;5;124m'[39m)

[0;31mAttributeError[0m: 'tuple' object has no attribute 'insert'
AttributeError: 'tuple' object has no attribute 'insert'

